config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
google_snow:
  outputs:
    prod:
      account: tn60754.ap-northeast-1.aws
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 15
      database: GIT_SAMPLE
      password: Shoki0908
      query_tag: normalization
      retry_all: true
      retry_on_database_errors: true
      role: PUBLIC
      schema: PYTHON_
      threads: 5
      type: snowflake
      user: KAWARADA
      warehouse: COMPUTE_WH
  target: prod
